### ISSUE TITLE
Drones programables e Inteligencia Artificial

### ISSUE THREAD

**Issue by profesorjlgarcia** [makersasturias/curso-101-drones#11]
Saludos, soy profesor técnico de Formación Profesional de ciclos formativos de Informática y estamos interesados en comenzar a conocer este mundo, para posteriormente aprender de qué forma poder programar este tipo de dispositivos y si podemos llegar a aplicar algún tipo de inteligencia artificial en ellos.

Gracias por vuestra atención.

**Comment by albfan** [comment]
Existen varias maneras de controlar un dron. En #5 se menciona Inav https://github.com/inavFlight/inav/wiki. Trataremos de hablar sobre control gps del vuelo de un dron.

Para programar el dron para hacer otras cosas, el medio que conozco es utilizar la tarjeta pixhawk conectarla a una raspberry pi y utilizar drone-kit para aplicar la lógica necesaria (al pasar por algún punto gps o similar). python puede utilizar opencv para procesar información de una camara y reaccionar a ello.

Todo esto queda fuera de un curso 101 pero si se pone en contacto con la asociación podemos buscar maneras de colaborar y dar un curso al respecto.
